default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jinro_rails
  password: jinro_rails
  host: localhost

development:
  <<: *default
  database: jinro_rails_development

test:
  <<: *default
  database: jinro_rails_test

production:
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
